[project]
name = "sapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "pytoml>=0.1.21",
    "selenium>=4.32.0",
    "typer>=0.15.3",
]
